name: Maven Package

on:
  push:
    branches: [ master ]
    paths:
      - 'MyApp/**' # Trigger for changes in the MyApp folder
      - 'taskappfe/**' # Trigger for changes in the taskappfe folder
  pull_request:
    branches: [ master ]
    paths:
      - 'MyApp/**'
      - 'taskappfe/**'

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  integration-unit-test:
    needs: [checkout-code]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }} # Only run if there are changes in MyApp folder
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run unit tests
        run: mvn test --file ./MyApp/pom.xml

  build_backend:
    runs-on: ubuntu-latest
    needs: [integration-unit-test]
    if: ${{ needs.integration-unit-test.result == 'success' }} # Only run if integration-unit-test job succeeded
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file ./MyApp/pom.xml -DskipTests
      - name: Build spring boot image
        run: docker build -t spring-app .
      - name: Display spring-app image
        run: docker images
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sowbarnigaa/backrepo:1

  build_frontend:
    name: frontend
    runs-on: ubuntu-latest
    needs: [build_backend]
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'taskappfe/') }} # Only run if there are changes in taskappfe folder
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'v20.11.0'
      - name: Build angular image
        run: |
          cd taskappfe
          docker build -t angular-app .
      - name: Display angular-app image
        run: docker images
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./taskappfe
          file: ./taskappfe/Dockerfile
          push: true
          tags: sowbarnigaa/frontrepo:1

  deploy:
    runs-on: self-hosted
    needs: [build_frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check images
        run: docker images
      - name: Build elastic search image
        run: docker pull docker.elastic.co/elasticsearch/elasticsearch:8.8.1
      - name: Build spring boot image
        run: docker pull sowbarnigaa/backrepo:latest
      - name: Build angular image
        run: docker pull sowbarnigaa/frontrepo:latest
      - name: Docker compose
        run: docker-compose -f ./MyApp/docker-compose.yaml up -d
