# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Maven Package and Docker Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
        env:
          discovery.type: single-node
          xpack.security.enabled: false
        options: >-
          --health-cmd "curl -f http://localhost:9200"
          --health-interval 20s
          --health-timeout 5s
          --health-retries 5 
        ports:
          - "9200:9200"
          - "9300:9300"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file ./MyApp/pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build Artifact with Maven
        run: mvn -B package --file ./MyApp/pom.xml -DskipTests

      - name: Create Docker Image
        run: |
          docker build -t sowbarnigaa/backrepo:latest -f ./path-to-Dockerfile .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push sowbarnigaa/backrepo:latest

