name: Maven Package

on:
  push:
    branches: [ master ]
    paths:
      - 'MyApp/**'
      - 'taskappfe/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'MyApp/**'
      - 'taskappfe/**'

jobs:
  build:
    name: backend
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.changed_files, 'MyApp/') }}
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
        env:
          discovery.type: single-node
          xpack.security.enabled: false
        options: >-
          --health-cmd "curl -f http://localhost:9200"
          --health-interval 20s
          --health-timeout 5s
          --health-retries 5 
        ports:
          - "9200:9200"
          - "9300:9300"
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
       mvn -B package --file ./MyApp/pom.xml
       cd MyApp
       mvn --batch-mode --update-snapshots verify
      
        # - run: mvn -B package --file ./MyApp/pom.xml -DskipTests
        # - run: mkdir staging && cp ./MyApp/target/myapptask.jar staging
        # - uses: actions/upload-artifact@v1
        #   with:
        #     name: Package
        #     path: staging
        
    - name: build spring boot image
      run: docker build -t spring-app .

    - name: display spring-app image
      run: docker images
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
              registry: docker.io
              username:  ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v4
      with:
              context: .
              file: ./Dockerfile
              push: true
              tags: sowbarnigaa/backrepo:1

  build_angular:
    name: frontend
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.changed_files, 'taskappfe/') }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'v20.11.0'

      - name: build angular image
        run: |
          cd taskappfe
          docker build -t angular-app .

      - name: display spring-app image
        run: docker images
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./taskappfe
          file: ./taskappfe/Dockerfile
          push: true
          tags: sowbarnigaa/frontrepo:1
      
          
  
